### ISSUE TITLE
Keyword "this" leads to syntax error

### ISSUE THREAD

**Issue by mterber** [mterber/ceu-editor#12]
When accessing organism variables or functions via **this** a syntax error is reported.

<pre><code>
class Test with
    var u8 k = 0;
do
    this.k = 5; // syntax error
end
</code></pre>

**Comment by langej** [comment]
mostly fixed by commit (7545fe0)

error remains at variables which consists of an uppercase-letter only

**Comment by langej** [comment]
Since there is no possibility in ceu to acces a variable with an uppercase-letter, can this be closed? @mterber

**Comment by mterber** [comment]
Yes. We should just keep that in mind in case the Céu grammar changes in future.
