### ISSUE TITLE
Vector appending not supported

### ISSUE THREAD

**Issue by mterber** [mterber/ceu-editor#20]
<pre><code>var u8[10] f;
f = [] .. f .. [5]; // '..' notation leads to syntax errors
</code></pre>

**Comment by langej** [comment]
caused by #23

**Comment by langej** [comment]
https://www.eclipse.org/forums/index.php/t/1078237/

**Comment by langej** [comment]
fixed with 1fb429637b0917658b52b754e65d0525c8950f8f
